import {RECORD_KEY} from '../../config/game-config.js';
export class GameEngine{
  constructor(root,settings,audio,env,characters,balloons){this.root=root;this.settingsCtrl=settings;this.audio=audio;this.env=env;this.characters=characters;this.balloons=balloons;this.state={mode:'attract',credits:0,score:0,record:Number(localStorage.getItem(RECORD_KEY)||0),timeLeft:60,paused:false,activeSide:null,lastSide:'right',warningSecond:null};this.timers={spawn:null,tick:null,return:null,voice:null};this.ui={hud:root.querySelector('#hud'),score:root.querySelector('#scoreValue'),time:root.querySelector('#timeValue'),record:root.querySelector('#recordValue'),credit:root.querySelector('#creditValue'),timeCard:root.querySelector('#timeCard'),panel:root.querySelector('#messagePanel'),badge:root.querySelector('#modeBadge'),main:root.querySelector('#mainMessage'),sub:root.querySelector('#subMessage'),countdown:root.querySelector('#countdown'),pause:root.querySelector('#pauseButton'),toast:root.querySelector('#toast'),burst:root.querySelector('#burstLayer')};this.resetAttract();this.applySettings()}
  get s(){return this.settingsCtrl.settings}
  applySettings(){this.env.apply();this.audio.updateMusic();if(this.state.mode==='attract')this.state.timeLeft=this.s.gameDuration;this.render()}
  clearTimers(){Object.values(this.timers).forEach(t=>clearTimeout(t));Object.keys(this.timers).forEach(k=>this.timers[k]=null)}
  render(){this.ui.score.textContent=this.state.score;this.ui.time.textContent=Math.max(0,Math.ceil(this.state.timeLeft));this.ui.record.textContent=this.state.record;this.ui.credit.textContent=this.state.credits;this.ui.timeCard.classList.toggle('warning',this.state.mode==='playing'&&this.state.timeLeft<=this.s.warningSeconds)}
  setMessage(main,sub='',badge=''){this.ui.main.textContent=main;this.ui.sub.textContent=sub;this.ui.badge.textContent=badge;this.ui.badge.style.display=badge?'':'none';this.ui.panel.classList.remove('is-hidden')}
  hideMessage(){this.ui.panel.classList.add('is-hidden')}
  resetAttract(){this.clearTimers();this.balloons.clear();this.state.mode='attract';this.state.score=0;this.state.timeLeft=this.s?.gameDuration||60;this.state.activeSide=null;this.state.paused=false;this.ui.hud.classList.add('is-hidden');this.ui.pause.classList.add('is-hidden');this.ui.countdown.classList.add('is-hidden');this.setMessage('PLEASE INSERT COIN','PRESS C TO INSERT COIN','DEMO MODE');this.render();this.scheduleAttractVoice()}
  scheduleAttractVoice(){clearTimeout(this.timers.voice);this.timers.voice=setTimeout(()=>{if(this.state.mode==='attract'){this.audio.voice('insertCoin','insertCoinVolume');this.scheduleAttractVoice()}},12000)}
  insertCoin(){this.audio.unlock();this.state.credits=Math.min(99,this.state.credits+1);this.audio.play('coin','coinVolume');this.audio.voice('credit','coinVolume',.92);this.setMessage(`CREDIT ${this.state.credits}`,'PRESS SPACE TO START','READY');this.render();this.toast('CREDIT ADDED');}
  async start(){if(this.state.mode==='playing'||this.state.mode==='countdown')return;if(this.state.credits<1){this.audio.voice('insertCoin','insertCoinVolume');this.setMessage('PLEASE INSERT COIN','PRESS C TO INSERT COIN','DEMO MODE');return}this.audio.unlock();if(this.s.fullscreenOnStart&&!document.fullscreenElement){document.documentElement.requestFullscreen?.().catch(()=>{})}this.state.credits--;this.state.score=0;this.state.timeLeft=this.s.gameDuration;this.state.mode='countdown';this.render();this.ui.hud.classList.remove('is-hidden');this.ui.pause.classList.remove('is-hidden');this.setMessage('GAME STARTING','GET READY','');this.audio.play('start','startVolume');this.audio.voice('start','startVolume');await new Promise(r=>setTimeout(r,650));this.hideMessage();for(const n of [3,2,1]){this.ui.countdown.textContent=n;this.ui.countdown.classList.remove('is-hidden');await new Promise(r=>setTimeout(r,620))}this.ui.countdown.textContent='GO!';await new Promise(r=>setTimeout(r,420));this.ui.countdown.classList.add('is-hidden');this.beginPlay()}
  beginPlay(){this.state.mode='playing';this.state.paused=false;this.endAt=performance.now()+this.state.timeLeft*1000;this.spawnNext(350);this.tick()}
  tick(){if(this.state.mode!=='playing')return;if(!this.state.paused){this.state.timeLeft=Math.max(0,(this.endAt-performance.now())/1000);const sec=Math.ceil(this.state.timeLeft);if(sec<=this.s.warningSeconds&&sec>0&&this.state.warningSecond!==sec){this.state.warningSecond=sec;this.audio.play('warning','warningVolume',.7);if(sec===this.s.warningSeconds)this.audio.voice('warning','warningVolume',.8)}this.render();if(this.state.timeLeft<=0){this.endGame();return}}this.timers.tick=setTimeout(()=>this.tick(),100)}
  spawnNext(delay=this.s.balloonInterval){clearTimeout(this.timers.spawn);this.timers.spawn=setTimeout(()=>{if(this.state.mode!=='playing'||this.state.paused)return;const side=Math.random()<.5?'left':'right';this.state.activeSide=side;this.state.lastSide=side;this.balloons.spawn(side);this.audio.play('launch','launchVolume',.78);this.timers.spawn=setTimeout(()=>this.spawnNext(0),this.s.balloonLife+180)},delay)}
  hit(side){if(this.state.mode!=='playing'||this.state.paused)return;const active=this.balloons.active;if(!active){this.wrong(side);return}if(active.side!==side){this.wrong(side);return}const popped=this.balloons.pop();this.state.activeSide=null;this.state.score+=this.s.scorePerHit;if(this.state.score>this.state.record){this.state.record=this.state.score;localStorage.setItem(RECORD_KEY,String(this.state.record))}this.audio.play('score','scoreVolume');this.audio.voice('score','scoreVolume',.62);this.characters.celebrate(side);this.confetti(side);this.render();clearTimeout(this.timers.spawn);this.spawnNext(360)}
  wrong(side){this.audio.play('wrong','wrongVolume');this.audio.voice('wrong','wrongVolume',.64);this.characters.wrong(side);this.toast('WRONG BASKET')}
  confetti(side){const count=Math.round(26*this.s.confettiPower/100);const x=side==='left'?'40.5%':'59.4%';const y='44%';const colors=['#ff4f5e','#ffd445','#5dc8ff','#65d66f','#b96cff','#ff7fc1'];const burst=document.createElement('div');burst.className='burst';burst.style.setProperty('--x',x);burst.style.setProperty('--y',y);for(let i=0;i<count;i++){const p=document.createElement('i');const a=Math.random()*Math.PI*2;const d=80+Math.random()*190;p.style.setProperty('--c',colors[i%colors.length]);p.style.setProperty('--dx',Math.cos(a)*d+'px');p.style.setProperty('--dy',(Math.sin(a)*d+80)+'px');p.style.setProperty('--rot',(Math.random()*900-450)+'deg');p.style.setProperty('--delay',(Math.random()*.08)+'s');burst.appendChild(p)}this.ui.burst.appendChild(burst);setTimeout(()=>burst.remove(),1100)}
  endGame(){this.clearTimers();this.balloons.clear();this.state.mode='gameover';this.state.timeLeft=0;this.render();this.ui.pause.classList.add('is-hidden');this.setMessage('GAME OVER',`SCORE ${this.state.score}   •   RECORD ${this.state.record}`,'');this.audio.play('gameOver','gameOverVolume');this.audio.voice('gameOver','gameOverVolume');this.timers.return=setTimeout(()=>this.resetAttract(),4200)}
  pause(){if(this.state.mode!=='playing')return;this.state.paused=!this.state.paused;if(this.state.paused){this.pauseAt=performance.now();this.setMessage('PAUSED','PRESS P TO RESUME','')}else{this.endAt+=performance.now()-this.pauseAt;this.hideMessage();if(!this.balloons.active)this.spawnNext(300)}this.ui.pause.textContent=this.state.paused?'▶':'Ⅱ'}
  toast(text){this.ui.toast.textContent=text;this.ui.toast.classList.remove('is-hidden');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>this.ui.toast.classList.add('is-hidden'),1000)}
}
