import {DEFAULTS,SETTINGS_KEY} from '../../config/game-config.js';
export class SettingsController{
  constructor(root,onChange){this.root=root;this.onChange=onChange;this.panel=root.querySelector('#settingsPanel');this.settings=this.load();this.map={gameDuration:'setGameDuration',scorePerHit:'setScorePerHit',balloonInterval:'setBalloonInterval',balloonLife:'setBalloonLife',warningSeconds:'setWarningSeconds',balloonScale:'setBalloonScale',fullscreenOnStart:'setFullscreenOnStart',masterVolume:'setMasterVolume',musicVolume:'setMusicVolume',voiceVolume:'setVoiceVolume',effectsVolume:'setEffectsVolume',insertCoinVolume:'setInsertCoinVolume',coinVolume:'setCoinVolume',startVolume:'setStartVolume',launchVolume:'setLaunchVolume',scoreVolume:'setScoreVolume',wrongVolume:'setWrongVolume',warningVolume:'setWarningVolume',gameOverVolume:'setGameOverVolume',confettiPower:'setConfettiPower',wheel:'setWheel',clouds:'setClouds',lights:'setLights',flags:'setFlags',decorBalloons:'setDecorBalloons',ambientConfetti:'setAmbientConfetti',blink:'setBlink'};this.bind();this.fill()}
  load(){try{return {...DEFAULTS,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return {...DEFAULTS}}}
  save(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(this.settings));this.onChange?.(this.settings)}
  fill(){for(const [key,id] of Object.entries(this.map)){const el=document.getElementById(id);if(!el)continue;if(el.type==='checkbox')el.checked=!!this.settings[key];else el.value=this.settings[key];const o=el.parentElement.querySelector('output');if(o)o.textContent=el.value+(key.toLowerCase().includes('volume')||key==='balloonScale'||key==='confettiPower'?'%':'')}}
  read(){for(const [key,id] of Object.entries(this.map)){const el=document.getElementById(id);if(!el)continue;this.settings[key]=el.type==='checkbox'?el.checked:Number(el.value)}return this.settings}
  bind(){document.querySelectorAll('.settings-tabs .tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.settings-tabs .tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.settings-page').forEach(p=>p.classList.toggle('active',p.dataset.page===b.dataset.tab))}));this.panel.querySelectorAll('input[type=range]').forEach(el=>el.addEventListener('input',()=>{const o=el.parentElement.querySelector('output');if(o)o.textContent=el.value+'%'}));document.getElementById('saveSettings').addEventListener('click',()=>{this.read();this.save();this.close()});document.getElementById('resetSettings').addEventListener('click',()=>{this.settings={...DEFAULTS};this.fill();this.save()});document.getElementById('settingsClose').addEventListener('click',()=>this.close())}
  open(){this.fill();this.panel.classList.add('open');this.panel.setAttribute('aria-hidden','false')}
  close(){this.panel.classList.remove('open');this.panel.setAttribute('aria-hidden','true')}
  toggle(){this.panel.classList.contains('open')?this.close():this.open()}
  isOpen(){return this.panel.classList.contains('open')}
}
